{
  "parameter(s)": [
    856.69,
    4
  ],
  "test_presence_of_inserted_element_at_index_4": [
    "failed",
    "IndexError: list index out of range",
    9e-05
  ],
  "test_presence_of_inserted_element": [
    "failed",
    "assert 856.69 in [[set(), set(), set(), set(), 856.69, set(), ...]]",
    0.00018
  ],
  "test_index_of_inserted_element": [
    "failed",
    "ValueError: 856.69 is not in list",
    0.0001
  ]
}