{
  "parameter(s)": [
    87
  ],
  "test_matrix_of_one_integer": [
    "failed",
    "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2",
    0.00025
  ],
  "test_horizontal_matrix": [
    "failed",
    "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2",
    0.0003
  ],
  "test_matrix_of_having_87_integers": [
    "failed",
    "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2",
    0.00034
  ]
}