{"category": "PytestAssertRewriteWarning", "filename": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", "lineno": 1277, "message": "Module already imported so cannot be rewritten: anyio", "$report_type": "WarningMessage", "when": "config", "location": ["/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", 1277, "_consider_importhook"]}
{"category": "PytestAssertRewriteWarning", "filename": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", "lineno": 1277, "message": "Module already imported so cannot be rewritten: anyio", "$report_type": "WarningMessage", "when": "config", "location": ["/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", 1277, "_consider_importhook"]}
{"pytest_version": "8.3.3", "$report_type": "SessionStart"}
{"nodeid": "tests50_96_2.py::test_list_of_strings_of_length_two", "location": ["tests50_96_2.py", 6, "test_list_of_strings_of_length_two"], "keywords": {"test_list_of_strings_of_length_two": 1, "tests50_96_2.py": 1, "Folder_96": 1, "": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00010127201676368713, "start": 1738505732.0741842, "stop": 1738505732.0742857, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "8893a8049759446bad6bbba4825a463b", "node": "<WorkerController gw0>"}
{"nodeid": "tests50_96_2.py::test_list_of_strings_of_length_two", "location": ["tests50_96_2.py", 6, "test_list_of_strings_of_length_two"], "keywords": {"test_list_of_strings_of_length_two": 1, "tests50_96_2.py": 1, "Folder_96": 1, "": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/data/ASE2024_GitHub/Turbulence-Benchmark-main/Command_T_D/Q50/command_results_2/Folder_96/generated_answer.py", "lineno": 4, "message": "UnboundLocalError: cannot access local variable 'b' where it is not associated with a value"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_strings_of_length_two():", "        l = ['aa', 'aa'] * (98 + 1)", ">       assert not if_contains_anagrams(l)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q50/command_results_2/Folder_96/tests50_96_2.py", "lineno": 9, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return 98 <= sum((1 for a in collections.Counter(s).values() if b in a for b in a))"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q50/command_results_2/Folder_96/generated_answer.py", "lineno": 4, "message": "in if_contains_anagrams"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": [">   return 98 <= sum((1 for a in collections.Counter(s).values() if b in a for b in a))", "E   UnboundLocalError: cannot access local variable 'b' where it is not associated with a value"], "reprfuncargs": {"args": [[".0", "<dict_valueiterator object at 0x7479a709e840>"]]}, "reprlocals": null, "reprfileloc": {"path": "Q50/command_results_2/Folder_96/generated_answer.py", "lineno": 4, "message": "UnboundLocalError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    def test_list_of_strings_of_length_two():", "        l = ['aa', 'aa'] * (98 + 1)", ">       assert not if_contains_anagrams(l)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q50/command_results_2/Folder_96/tests50_96_2.py", "lineno": 9, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return 98 <= sum((1 for a in collections.Counter(s).values() if b in a for b in a))"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q50/command_results_2/Folder_96/generated_answer.py", "lineno": 4, "message": "in if_contains_anagrams"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": [">   return 98 <= sum((1 for a in collections.Counter(s).values() if b in a for b in a))", "E   UnboundLocalError: cannot access local variable 'b' where it is not associated with a value"], "reprfuncargs": {"args": [[".0", "<dict_valueiterator object at 0x7479a709e840>"]]}, "reprlocals": null, "reprfileloc": {"path": "Q50/command_results_2/Folder_96/generated_answer.py", "lineno": 4, "message": "UnboundLocalError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/data/ASE2024_GitHub/Turbulence-Benchmark-main/Command_T_D/Q50/command_results_2/Folder_96/generated_answer.py", "lineno": 4, "message": "UnboundLocalError: cannot access local variable 'b' where it is not associated with a value"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00016286782920360565, "start": 1738505732.0744119, "stop": 1738505732.074575, "extras": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "8893a8049759446bad6bbba4825a463b", "node": "<WorkerController gw0>"}
{"nodeid": "tests50_96_2.py::test_list_of_strings_of_length_two", "location": ["tests50_96_2.py", 6, "test_list_of_strings_of_length_two"], "keywords": {"test_list_of_strings_of_length_two": 1, "tests50_96_2.py": 1, "Folder_96": 1, "": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.00012189242988824844, "start": 1738505732.0838656, "stop": 1738505732.083988, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "8893a8049759446bad6bbba4825a463b", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
