{
  "parameter(s)": [
    -185
  ],
  "test_matrix_of_single_number_equal_to_sum": [
    "failed",
    "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2",
    0.00024
  ],
  "test_matrix_of_several_numbers": [
    "failed",
    "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2",
    0.00045
  ],
  "test_matrix_of_single_number_and_zeros": [
    "failed",
    "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2",
    0.00027
  ]
}