{"category": "PytestAssertRewriteWarning", "filename": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", "lineno": 1204, "message": "Module already imported so cannot be rewritten: anyio", "$report_type": "WarningMessage", "when": "config", "location": ["/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", 1204, "_consider_importhook"]}
{"category": "PytestAssertRewriteWarning", "filename": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", "lineno": 1204, "message": "Module already imported so cannot be rewritten: anyio", "$report_type": "WarningMessage", "when": "config", "location": ["/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", 1204, "_consider_importhook"]}
{"pytest_version": "7.4.4", "$report_type": "SessionStart"}
{"nodeid": "tests57_99_5.py::test_matrix_of_single_number_equal_to_sum", "location": ["tests57_99_5.py", 17, "test_matrix_of_single_number_equal_to_sum"], "keywords": {"test_matrix_of_single_number_equal_to_sum": 1, "__wrapped__": 1, "tests57_99_5.py": 1, "Folder_99": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.0001582519616931677, "start": 1731152379.6893332, "stop": 1731152379.6894922, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "3dde6c6aa0ba4c049af36a3df994579c", "node": "<WorkerController gw0>"}
{"nodeid": "tests57_99_5.py::test_matrix_of_several_numbers", "location": ["tests57_99_5.py", 29, "test_matrix_of_several_numbers"], "keywords": {"test_matrix_of_several_numbers": 1, "__wrapped__": 1, "tests57_99_5.py": 1, "Folder_99": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00015251291915774345, "start": 1731152379.6892774, "stop": 1731152379.6894302, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "3dde6c6aa0ba4c049af36a3df994579c", "node": "<WorkerController gw1>"}
{"nodeid": "tests57_99_5.py::test_matrix_of_single_number_and_zeros", "location": ["tests57_99_5.py", 51, "test_matrix_of_single_number_and_zeros"], "keywords": {"test_matrix_of_single_number_and_zeros": 1, "__wrapped__": 1, "tests57_99_5.py": 1, "Folder_99": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00016722804866731167, "start": 1731152379.7283561, "stop": 1731152379.728524, "$report_type": "TestReport", "item_index": 4, "worker_id": "gw2", "testrun_uid": "3dde6c6aa0ba4c049af36a3df994579c", "node": "<WorkerController gw2>"}
{"nodeid": "tests57_99_5.py::test_matrix_of_single_number_equal_to_sum", "location": ["tests57_99_5.py", 17, "test_matrix_of_single_number_equal_to_sum"], "keywords": {"test_matrix_of_single_number_equal_to_sum": 1, "__wrapped__": 1, "tests57_99_5.py": 1, "Folder_99": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_single_number_equal_to_sum():", "        input_matrix = np.matrix([[-185]])", ">       assert submatrix_with_particular_sum(input_matrix) == [[[-185]]]"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/tests57_99_5.py", "lineno": 21, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return np.where(np.sum(matrix, axis=2) == -185)[0].tolist()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/generated_answer.py", "lineno": 4, "message": "in submatrix_with_particular_sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 2313, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return reduction(axis=axis, out=out, **passkwargs)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 86, "message": "in _wrapreduction"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return N.ndarray.sum(self, axis, dtype, out, keepdims=True)._collapse(axis)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", "lineno": 320, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,", "             initial=_NoValue, where=True):", ">       return umr_sum(a, axis, dtype, out, keepdims, initial, where)", "E       numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"], "reprfuncargs": {"args": [["a", "matrix([[-185]])"], ["axis", "2"], ["dtype", "None"], ["out", "None"], ["keepdims", "True"], ["initial", "<no value>"], ["where", "True"]]}, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "AxisError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_single_number_equal_to_sum():", "        input_matrix = np.matrix([[-185]])", ">       assert submatrix_with_particular_sum(input_matrix) == [[[-185]]]"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/tests57_99_5.py", "lineno": 21, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return np.where(np.sum(matrix, axis=2) == -185)[0].tolist()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/generated_answer.py", "lineno": 4, "message": "in submatrix_with_particular_sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 2313, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return reduction(axis=axis, out=out, **passkwargs)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 86, "message": "in _wrapreduction"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return N.ndarray.sum(self, axis, dtype, out, keepdims=True)._collapse(axis)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", "lineno": 320, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,", "             initial=_NoValue, where=True):", ">       return umr_sum(a, axis, dtype, out, keepdims, initial, where)", "E       numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"], "reprfuncargs": {"args": [["a", "matrix([[-185]])"], ["axis", "2"], ["dtype", "None"], ["out", "None"], ["keepdims", "True"], ["initial", "<no value>"], ["where", "True"]]}, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "AxisError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.0002351449802517891, "start": 1731152379.6897376, "stop": 1731152379.6899734, "extras": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "3dde6c6aa0ba4c049af36a3df994579c", "node": "<WorkerController gw0>"}
{"nodeid": "tests57_99_5.py::test_matrix_of_single_number_equal_to_sum", "location": ["tests57_99_5.py", 17, "test_matrix_of_single_number_equal_to_sum"], "keywords": {"test_matrix_of_single_number_equal_to_sum": 1, "__wrapped__": 1, "tests57_99_5.py": 1, "Folder_99": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.00011363811790943146, "start": 1731152379.7643979, "stop": 1731152379.764512, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "3dde6c6aa0ba4c049af36a3df994579c", "node": "<WorkerController gw0>"}
{"nodeid": "tests57_99_5.py::test_matrix_of_several_numbers", "location": ["tests57_99_5.py", 29, "test_matrix_of_several_numbers"], "keywords": {"test_matrix_of_several_numbers": 1, "__wrapped__": 1, "tests57_99_5.py": 1, "Folder_99": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_several_numbers():", "        if -185 <= 0:", "            row = '1 2 3 4 5 6 7 8 9'", "            input_matrix = np.matrix(f'{row}; {row}; {row}')", "        else:", "            row = '-1 -2 -3 -4 -5 -6 -7 -8 -9'", "            input_matrix = np.matrix(f'{row}; {row}; {row}')", ">       assert not submatrix_with_particular_sum(input_matrix)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/tests57_99_5.py", "lineno": 38, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return np.where(np.sum(matrix, axis=2) == -185)[0].tolist()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/generated_answer.py", "lineno": 4, "message": "in submatrix_with_particular_sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 2313, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return reduction(axis=axis, out=out, **passkwargs)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 86, "message": "in _wrapreduction"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return N.ndarray.sum(self, axis, dtype, out, keepdims=True)._collapse(axis)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", "lineno": 320, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,", "             initial=_NoValue, where=True):", ">       return umr_sum(a, axis, dtype, out, keepdims, initial, where)", "E       numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"], "reprfuncargs": {"args": [["a", "matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9],\n        [1, 2, 3, 4, 5, 6, 7, 8, 9],\n        [1, 2, 3, 4, 5, 6, 7, 8, 9]])"], ["axis", "2"], ["dtype", "None"], ["out", "None"], ["keepdims", "True"], ["initial", "<no value>"], ["where", "True"]]}, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "AxisError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_several_numbers():", "        if -185 <= 0:", "            row = '1 2 3 4 5 6 7 8 9'", "            input_matrix = np.matrix(f'{row}; {row}; {row}')", "        else:", "            row = '-1 -2 -3 -4 -5 -6 -7 -8 -9'", "            input_matrix = np.matrix(f'{row}; {row}; {row}')", ">       assert not submatrix_with_particular_sum(input_matrix)"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/tests57_99_5.py", "lineno": 38, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return np.where(np.sum(matrix, axis=2) == -185)[0].tolist()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/generated_answer.py", "lineno": 4, "message": "in submatrix_with_particular_sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 2313, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return reduction(axis=axis, out=out, **passkwargs)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 86, "message": "in _wrapreduction"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return N.ndarray.sum(self, axis, dtype, out, keepdims=True)._collapse(axis)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", "lineno": 320, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,", "             initial=_NoValue, where=True):", ">       return umr_sum(a, axis, dtype, out, keepdims, initial, where)", "E       numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"], "reprfuncargs": {"args": [["a", "matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9],\n        [1, 2, 3, 4, 5, 6, 7, 8, 9],\n        [1, 2, 3, 4, 5, 6, 7, 8, 9]])"], ["axis", "2"], ["dtype", "None"], ["out", "None"], ["keepdims", "True"], ["initial", "<no value>"], ["where", "True"]]}, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "AxisError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.0004543599206954241, "start": 1731152379.6896672, "stop": 1731152379.6901221, "extras": [], "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "3dde6c6aa0ba4c049af36a3df994579c", "node": "<WorkerController gw1>"}
{"nodeid": "tests57_99_5.py::test_matrix_of_several_numbers", "location": ["tests57_99_5.py", 29, "test_matrix_of_several_numbers"], "keywords": {"test_matrix_of_several_numbers": 1, "__wrapped__": 1, "tests57_99_5.py": 1, "Folder_99": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.00010371394455432892, "start": 1731152379.768424, "stop": 1731152379.7685285, "$report_type": "TestReport", "item_index": 2, "worker_id": "gw1", "testrun_uid": "3dde6c6aa0ba4c049af36a3df994579c", "node": "<WorkerController gw1>"}
{"nodeid": "tests57_99_5.py::test_matrix_of_single_number_and_zeros", "location": ["tests57_99_5.py", 51, "test_matrix_of_single_number_and_zeros"], "keywords": {"test_matrix_of_single_number_and_zeros": 1, "__wrapped__": 1, "tests57_99_5.py": 1, "Folder_99": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_single_number_and_zeros():", "        if -185 == 0:", "            element = 1", "        else:", "            element = 0", "        for i in range(1, 11):", "            mat = ''", "            for j in range(i):", "                row = (f'{element} ' * i) + ';'", "                mat += row", "            mat = mat[:-1]", "            mat = np.matrix(mat)", "            mat[0, 0] = -185", "            if -185 == 0:", "                assert len(submatrix_with_particular_sum(mat)) == 1", "            else:", ">               assert len(submatrix_with_particular_sum(mat)) == i * i"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/tests57_99_5.py", "lineno": 69, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return np.where(np.sum(matrix, axis=2) == -185)[0].tolist()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/generated_answer.py", "lineno": 4, "message": "in submatrix_with_particular_sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 2313, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return reduction(axis=axis, out=out, **passkwargs)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 86, "message": "in _wrapreduction"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return N.ndarray.sum(self, axis, dtype, out, keepdims=True)._collapse(axis)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", "lineno": 320, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,", "             initial=_NoValue, where=True):", ">       return umr_sum(a, axis, dtype, out, keepdims, initial, where)", "E       numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"], "reprfuncargs": {"args": [["a", "matrix([[-185]])"], ["axis", "2"], ["dtype", "None"], ["out", "None"], ["keepdims", "True"], ["initial", "<no value>"], ["where", "True"]]}, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "AxisError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_single_number_and_zeros():", "        if -185 == 0:", "            element = 1", "        else:", "            element = 0", "        for i in range(1, 11):", "            mat = ''", "            for j in range(i):", "                row = (f'{element} ' * i) + ';'", "                mat += row", "            mat = mat[:-1]", "            mat = np.matrix(mat)", "            mat[0, 0] = -185", "            if -185 == 0:", "                assert len(submatrix_with_particular_sum(mat)) == 1", "            else:", ">               assert len(submatrix_with_particular_sum(mat)) == i * i"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/tests57_99_5.py", "lineno": 69, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    return np.where(np.sum(matrix, axis=2) == -185)[0].tolist()"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q57/command_results_5/Folder_99/generated_answer.py", "lineno": 4, "message": "in submatrix_with_particular_sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 2313, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return reduction(axis=axis, out=out, **passkwargs)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/fromnumeric.py", "lineno": 86, "message": "in _wrapreduction"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return N.ndarray.sum(self, axis, dtype, out, keepdims=True)._collapse(axis)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", "lineno": 320, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,", "             initial=_NoValue, where=True):", ">       return umr_sum(a, axis, dtype, out, keepdims, initial, where)", "E       numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"], "reprfuncargs": {"args": [["a", "matrix([[-185]])"], ["axis", "2"], ["dtype", "None"], ["out", "None"], ["keepdims", "True"], ["initial", "<no value>"], ["where", "True"]]}, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "AxisError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00027392501942813396, "start": 1731152379.728776, "stop": 1731152379.7290504, "extras": [], "$report_type": "TestReport", "item_index": 4, "worker_id": "gw2", "testrun_uid": "3dde6c6aa0ba4c049af36a3df994579c", "node": "<WorkerController gw2>"}
{"nodeid": "tests57_99_5.py::test_matrix_of_single_number_and_zeros", "location": ["tests57_99_5.py", 51, "test_matrix_of_single_number_and_zeros"], "keywords": {"test_matrix_of_single_number_and_zeros": 1, "__wrapped__": 1, "tests57_99_5.py": 1, "Folder_99": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.00010159099474549294, "start": 1731152379.7700922, "stop": 1731152379.7701945, "$report_type": "TestReport", "item_index": 4, "worker_id": "gw2", "testrun_uid": "3dde6c6aa0ba4c049af36a3df994579c", "node": "<WorkerController gw2>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
