{"category": "PytestAssertRewriteWarning", "filename": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", "lineno": 1277, "message": "Module already imported so cannot be rewritten: anyio", "$report_type": "WarningMessage", "when": "config", "location": ["/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", 1277, "_consider_importhook"]}
{"category": "PytestAssertRewriteWarning", "filename": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", "lineno": 1277, "message": "Module already imported so cannot be rewritten: anyio", "$report_type": "WarningMessage", "when": "config", "location": ["/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/_pytest/config/__init__.py", 1277, "_consider_importhook"]}
{"pytest_version": "8.3.3", "$report_type": "SessionStart"}
{"nodeid": "tests57_98_2.py::test_matrix_of_single_number_equal_to_sum", "location": ["tests57_98_2.py", 17, "test_matrix_of_single_number_equal_to_sum"], "keywords": {"test_matrix_of_single_number_equal_to_sum": 1, "__wrapped__": 1, "tests57_98_2.py": 1, "Folder_98": 1, "": 1}, "outcome": "passed", "longrepr": null, "when": "setup", "user_properties": [], "sections": [], "duration": 0.00038648582994937897, "start": 1738460508.8223698, "stop": 1738460508.8227568, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "47100ce65bf04a298a88d2d42ea21558", "node": "<WorkerController gw0>"}
{"nodeid": "tests57_98_2.py::test_matrix_of_single_number_equal_to_sum", "location": ["tests57_98_2.py", 17, "test_matrix_of_single_number_equal_to_sum"], "keywords": {"test_matrix_of_single_number_equal_to_sum": 1, "__wrapped__": 1, "tests57_98_2.py": 1, "Folder_98": 1, "": 1}, "outcome": "failed", "longrepr": {"reprcrash": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"}, "reprtraceback": {"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_single_number_equal_to_sum():", "        input_matrix = np.matrix([[0]])", ">       assert submatrix_with_particular_sum(input_matrix) == [[[0]]]"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q57/Phi_3_results_2/Folder_98/tests57_98_2.py", "lineno": 21, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    submatrix = np.subtract(matrix[i:k + 1, j:l + 1], matrix[:k - i + 1, :l - j + 1]).sum(axis=(1, 2))"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q57/Phi_3_results_2/Folder_98/generated_answer.py", "lineno": 9, "message": "in submatrix_with_particular_sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return N.ndarray.sum(self, axis, dtype, out, keepdims=True)._collapse(axis)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", "lineno": 320, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,", "             initial=_NoValue, where=True):", ">       return umr_sum(a, axis, dtype, out, keepdims, initial, where)", "E       numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"], "reprfuncargs": {"args": [["a", "matrix([[0]])"], ["axis", "(1, 2)"], ["dtype", "None"], ["out", "None"], ["keepdims", "True"], ["initial", "<no value>"], ["where", "True"]]}, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "AxisError"}, "style": "long"}}], "extraline": null, "style": "long"}, "sections": [], "chain": [[{"reprentries": [{"type": "ReprEntry", "data": {"lines": ["    @ignore_warnings", "    def test_matrix_of_single_number_equal_to_sum():", "        input_matrix = np.matrix([[0]])", ">       assert submatrix_with_particular_sum(input_matrix) == [[[0]]]"], "reprfuncargs": {"args": []}, "reprlocals": null, "reprfileloc": {"path": "Q57/Phi_3_results_2/Folder_98/tests57_98_2.py", "lineno": 21, "message": ""}, "style": "long"}}, {"type": "ReprEntry", "data": {"lines": ["    submatrix = np.subtract(matrix[i:k + 1, j:l + 1], matrix[:k - i + 1, :l - j + 1]).sum(axis=(1, 2))"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "Q57/Phi_3_results_2/Folder_98/generated_answer.py", "lineno": 9, "message": "in submatrix_with_particular_sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    return N.ndarray.sum(self, axis, dtype, out, keepdims=True)._collapse(axis)"], "reprfuncargs": null, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/matrixlib/defmatrix.py", "lineno": 320, "message": "in sum"}, "style": "short"}}, {"type": "ReprEntry", "data": {"lines": ["    def _sum(a, axis=None, dtype=None, out=None, keepdims=False,", "             initial=_NoValue, where=True):", ">       return umr_sum(a, axis, dtype, out, keepdims, initial, where)", "E       numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"], "reprfuncargs": {"args": [["a", "matrix([[0]])"], ["axis", "(1, 2)"], ["dtype", "None"], ["out", "None"], ["keepdims", "True"], ["initial", "<no value>"], ["where", "True"]]}, "reprlocals": null, "reprfileloc": {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "AxisError"}, "style": "long"}}], "extraline": null, "style": "long"}, {"path": "/data/miniconda3/envs/benchmark/lib/python3.12/site-packages/numpy/core/_methods.py", "lineno": 49, "message": "numpy.exceptions.AxisError: axis 2 is out of bounds for array of dimension 2"}, null]]}, "when": "call", "user_properties": [], "sections": [], "duration": 0.00044444575905799866, "start": 1738460508.8230433, "stop": 1738460508.8234882, "extras": [], "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "47100ce65bf04a298a88d2d42ea21558", "node": "<WorkerController gw0>"}
{"nodeid": "tests57_98_2.py::test_matrix_of_single_number_equal_to_sum", "location": ["tests57_98_2.py", 17, "test_matrix_of_single_number_equal_to_sum"], "keywords": {"test_matrix_of_single_number_equal_to_sum": 1, "__wrapped__": 1, "tests57_98_2.py": 1, "Folder_98": 1, "": 1}, "outcome": "passed", "longrepr": null, "when": "teardown", "user_properties": [], "sections": [], "duration": 0.0005309786647558212, "start": 1738460508.84822, "stop": 1738460508.848752, "$report_type": "TestReport", "item_index": 0, "worker_id": "gw0", "testrun_uid": "47100ce65bf04a298a88d2d42ea21558", "node": "<WorkerController gw0>"}
{"exitstatus": 2, "$report_type": "SessionFinish"}
