{
  "parameter(s)": [
    370,
    918
  ],
  "test_large_range": [
    "failed",
    "TypeError: chain.from_iterable() takes exactly one argument (2 given)",
    0.00017
  ],
  "test_lengths": [
    "failed",
    "TypeError: chain.from_iterable() takes exactly one argument (2 given)",
    0.00015
  ],
  "test_even_range": [
    "failed",
    "TypeError: chain.from_iterable() takes exactly one argument (2 given)",
    0.00016
  ]
}